"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Request(google.protobuf.message.Message):
    """Unary request."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FILL_USERNAME_FIELD_NUMBER: builtins.int
    FILL_OAUTH_SCOPE_FIELD_NUMBER: builtins.int
    fill_username: builtins.bool
    """Whether Response should include username."""

    fill_oauth_scope: builtins.bool
    """Whether Response should include OAuth scope."""

    def __init__(self,
        *,
        fill_username: builtins.bool = ...,
        fill_oauth_scope: builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["fill_oauth_scope",b"fill_oauth_scope","fill_username",b"fill_username"]) -> None: ...
global___Request = Request

class Response(google.protobuf.message.Message):
    """Unary response, as configured by the request."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    USERNAME_FIELD_NUMBER: builtins.int
    OAUTH_SCOPE_FIELD_NUMBER: builtins.int
    username: typing.Text
    """The user the request came from, for verifying authentication was
    successful.
    """

    oauth_scope: typing.Text
    """OAuth scope."""

    def __init__(self,
        *,
        username: typing.Text = ...,
        oauth_scope: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["oauth_scope",b"oauth_scope","username",b"username"]) -> None: ...
global___Response = Response
