"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class MongoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    METHOD_FIELD_NUMBER: builtins.int
    ARGS_FIELD_NUMBER: builtins.int
    method: typing.Text
    """fn = getattr(pymongo, method)"""

    args: typing.Text
    """out = eval(fn, args)"""

    def __init__(self,
        *,
        method: typing.Text = ...,
        args: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["args",b"args","method",b"method"]) -> None: ...
global___MongoRequest = MongoRequest

class MongoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RESULT_BINARY_FIELD_NUMBER: builtins.int
    RESULT_STRING_FIELD_NUMBER: builtins.int
    TRACEBACK_FIELD_NUMBER: builtins.int
    result_binary: builtins.bytes
    """binary json string"""

    result_string: typing.Text
    """utf-8 encoded json string"""

    traceback: typing.Text
    """or get the full line by line traceback or exception"""

    def __init__(self,
        *,
        result_binary: builtins.bytes = ...,
        result_string: typing.Text = ...,
        traceback: typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["response",b"response","result_binary",b"result_binary","result_string",b"result_string","traceback",b"traceback"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["response",b"response","result_binary",b"result_binary","result_string",b"result_string","traceback",b"traceback"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["response",b"response"]) -> typing.Optional[typing_extensions.Literal["result_binary","result_string","traceback"]]: ...
global___MongoResponse = MongoResponse
