# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: one.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import two_pb2 as two__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tone.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\ttwo.proto\"C\n\nOneMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\'\n\x03now\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\x98\x01\n\x07Scooper\x12!\n\x05Hello\x12\x0b.OneMessage\x1a\x0b.OneMessage\x12>\n\x08WhatTime\x12\x16.google.protobuf.Empty\x1a\x1a.google.protobuf.Timestamp\x12*\n\x0b\x44oubleHello\x12\x0b.OneMessage\x1a\x0e.DoubleMessageb\x06proto3')



_ONEMESSAGE = DESCRIPTOR.message_types_by_name['OneMessage']
OneMessage = _reflection.GeneratedProtocolMessageType('OneMessage', (_message.Message,), {
  'DESCRIPTOR' : _ONEMESSAGE,
  '__module__' : 'one_pb2'
  # @@protoc_insertion_point(class_scope:OneMessage)
  })
_sym_db.RegisterMessage(OneMessage)

_SCOOPER = DESCRIPTOR.services_by_name['Scooper']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ONEMESSAGE._serialized_start=86
  _ONEMESSAGE._serialized_end=153
  _SCOOPER._serialized_start=156
  _SCOOPER._serialized_end=308
# @@protoc_insertion_point(module_scope)
