# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: two.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttwo.proto\"\x1d\n\rDoubleMessage\x12\x0c\n\x04name\x18\x01 \x01(\tb\x06proto3')



_DOUBLEMESSAGE = DESCRIPTOR.message_types_by_name['DoubleMessage']
DoubleMessage = _reflection.GeneratedProtocolMessageType('DoubleMessage', (_message.Message,), {
  'DESCRIPTOR' : _DOUBLEMESSAGE,
  '__module__' : 'two_pb2'
  # @@protoc_insertion_point(class_scope:DoubleMessage)
  })
_sym_db.RegisterMessage(DoubleMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DOUBLEMESSAGE._serialized_start=13
  _DOUBLEMESSAGE._serialized_end=42
# @@protoc_insertion_point(module_scope)
