# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: examples/ice_cream/ice_cream.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"examples/ice_cream/ice_cream.proto\"A\n\x0fIceCreamRequest\x12\x17\n\x06\x66lavor\x18\x01 \x01(\x0e\x32\x07.Flavor\x12\x15\n\rcustomer_name\x18\x02 \x01(\t\"L\n\x08IceCream\x12\x17\n\x06\x66lavor\x18\x01 \x01(\x0e\x32\x07.Flavor\x12\x15\n\rcustomer_name\x18\x02 \x01(\t\x12\x10\n\x08\x66inished\x18\x03 \x01(\x08\"\x1e\n\x0bTissuePaper\x12\x0f\n\x07message\x18\x01 \x01(\t*4\n\x06\x46lavor\x12\r\n\tCHOCOLATE\x10\x00\x12\x0b\n\x07VANILLA\x10\x01\x12\x0e\n\nSTRAWBERRY\x10\x02\x32\x64\n\x0cIceCreamShop\x12*\n\x0bGetIceCream\x12\x10.IceCreamRequest\x1a\t.IceCream\x12(\n\rThrowIceCream\x12\t.IceCream\x1a\x0c.TissuePaperb\x06proto3')

_FLAVOR = DESCRIPTOR.enum_types_by_name['Flavor']
Flavor = enum_type_wrapper.EnumTypeWrapper(_FLAVOR)
CHOCOLATE = 0
VANILLA = 1
STRAWBERRY = 2


_ICECREAMREQUEST = DESCRIPTOR.message_types_by_name['IceCreamRequest']
_ICECREAM = DESCRIPTOR.message_types_by_name['IceCream']
_TISSUEPAPER = DESCRIPTOR.message_types_by_name['TissuePaper']
IceCreamRequest = _reflection.GeneratedProtocolMessageType('IceCreamRequest', (_message.Message,), {
  'DESCRIPTOR' : _ICECREAMREQUEST,
  '__module__' : 'examples.ice_cream.ice_cream_pb2'
  # @@protoc_insertion_point(class_scope:IceCreamRequest)
  })
_sym_db.RegisterMessage(IceCreamRequest)

IceCream = _reflection.GeneratedProtocolMessageType('IceCream', (_message.Message,), {
  'DESCRIPTOR' : _ICECREAM,
  '__module__' : 'examples.ice_cream.ice_cream_pb2'
  # @@protoc_insertion_point(class_scope:IceCream)
  })
_sym_db.RegisterMessage(IceCream)

TissuePaper = _reflection.GeneratedProtocolMessageType('TissuePaper', (_message.Message,), {
  'DESCRIPTOR' : _TISSUEPAPER,
  '__module__' : 'examples.ice_cream.ice_cream_pb2'
  # @@protoc_insertion_point(class_scope:TissuePaper)
  })
_sym_db.RegisterMessage(TissuePaper)

_ICECREAMSHOP = DESCRIPTOR.services_by_name['IceCreamShop']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FLAVOR._serialized_start=215
  _FLAVOR._serialized_end=267
  _ICECREAMREQUEST._serialized_start=38
  _ICECREAMREQUEST._serialized_end=103
  _ICECREAM._serialized_start=105
  _ICECREAM._serialized_end=181
  _TISSUEPAPER._serialized_start=183
  _TISSUEPAPER._serialized_end=213
  _ICECREAMSHOP._serialized_start=269
  _ICECREAMSHOP._serialized_end=369
# @@protoc_insertion_point(module_scope)
