"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Flavor:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _FlavorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Flavor.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CHOCOLATE: _Flavor.ValueType  # 0
    VANILLA: _Flavor.ValueType  # 1
    STRAWBERRY: _Flavor.ValueType  # 2
class Flavor(_Flavor, metaclass=_FlavorEnumTypeWrapper):
    pass

CHOCOLATE: Flavor.ValueType  # 0
VANILLA: Flavor.ValueType  # 1
STRAWBERRY: Flavor.ValueType  # 2
global___Flavor = Flavor


class IceCreamRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FLAVOR_FIELD_NUMBER: builtins.int
    CUSTOMER_NAME_FIELD_NUMBER: builtins.int
    flavor: global___Flavor.ValueType
    """"""

    customer_name: typing.Text
    """name of the customer"""

    def __init__(self,
        *,
        flavor: global___Flavor.ValueType = ...,
        customer_name: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["customer_name",b"customer_name","flavor",b"flavor"]) -> None: ...
global___IceCreamRequest = IceCreamRequest

class IceCream(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FLAVOR_FIELD_NUMBER: builtins.int
    CUSTOMER_NAME_FIELD_NUMBER: builtins.int
    FINISHED_FIELD_NUMBER: builtins.int
    flavor: global___Flavor.ValueType
    customer_name: typing.Text
    finished: builtins.bool
    def __init__(self,
        *,
        flavor: global___Flavor.ValueType = ...,
        customer_name: typing.Text = ...,
        finished: builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["customer_name",b"customer_name","finished",b"finished","flavor",b"flavor"]) -> None: ...
global___IceCream = IceCream

class TissuePaper(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MESSAGE_FIELD_NUMBER: builtins.int
    message: typing.Text
    def __init__(self,
        *,
        message: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message",b"message"]) -> None: ...
global___TissuePaper = TissuePaper
