# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: examples/mongo/mongo_rpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x65xamples/mongo/mongo_rpc.proto\",\n\x0cMongoRequest\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x01(\t\"b\n\rMongoResponse\x12\x17\n\rresult_binary\x18\x01 \x01(\x0cH\x00\x12\x17\n\rresult_string\x18\x02 \x01(\tH\x00\x12\x13\n\ttraceback\x18\x03 \x01(\tH\x00\x42\n\n\x08response27\n\x0cMongoJsonRPC\x12\'\n\x04\x43\x61ll\x12\r.MongoRequest\x1a\x0e.MongoResponse\"\x00\x62\x06proto3')



_MONGOREQUEST = DESCRIPTOR.message_types_by_name['MongoRequest']
_MONGORESPONSE = DESCRIPTOR.message_types_by_name['MongoResponse']
MongoRequest = _reflection.GeneratedProtocolMessageType('MongoRequest', (_message.Message,), {
  'DESCRIPTOR' : _MONGOREQUEST,
  '__module__' : 'examples.mongo.mongo_rpc_pb2'
  # @@protoc_insertion_point(class_scope:MongoRequest)
  })
_sym_db.RegisterMessage(MongoRequest)

MongoResponse = _reflection.GeneratedProtocolMessageType('MongoResponse', (_message.Message,), {
  'DESCRIPTOR' : _MONGORESPONSE,
  '__module__' : 'examples.mongo.mongo_rpc_pb2'
  # @@protoc_insertion_point(class_scope:MongoResponse)
  })
_sym_db.RegisterMessage(MongoResponse)

_MONGOJSONRPC = DESCRIPTOR.services_by_name['MongoJsonRPC']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MONGOREQUEST._serialized_start=34
  _MONGOREQUEST._serialized_end=78
  _MONGORESPONSE._serialized_start=80
  _MONGORESPONSE._serialized_end=178
  _MONGOJSONRPC._serialized_start=180
  _MONGOJSONRPC._serialized_end=235
# @@protoc_insertion_point(module_scope)
