name: Export as Submodule
on:
  push:
    branches: [main]
    paths:
      - "yql/**"
  workflow_dispatch:
jobs:
  export-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2 

      - name: Commit Submodule
        working-directory: "yql/"
        run: |
          git config --global user.name "Yash Bonde"
          git config --global user.email "bonde.yash97@gmail.com"
          git add .
          git commit -am "New submodule ${GITHUB_SHA::8}" || echo up to date
          git push origin HEAD:yql_submodule
